---
- name: Install Prerequisites
  apt:
    name: "{{ packages }}"
    update_cache: "{{ apt_get_update_cache }}"
    cache_valid_time: 1800
    state: "latest"
    force_apt_get: True
  when: ( apt_get_update_cache is defined ) and ( apt_get_update_cache|bool == True )
