all:
  hosts:
  children:
    mailservers:
      hosts:
        mail.mailad.cu:
# Set your ip if your dns is not configured to resolve your hostname
          ansible_host: 10.0.3.7
          ansible_python_interpreter: /usr/bin/python3
